# scripts/import_direction_lookup.py
from __future__ import annotations

import csv

from sitrepc2.config.paths import source_direction_lookup_path


def import_directions(conn) -> None:
    """
    Import directions from direction_lookup.csv into:

      - directions(dir_id, name, anchor_cid)

    The CSV is expected to have headers:

      name,anchor_cid

    dir_id is auto-generated by SQLite (AUTOINCREMENT).
    """
    path = source_direction_lookup_path()
    print(f"📥 Importing direction data from {path} ...")

    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        required_fields = {
            "name",
            "anchor_cid",
        }
        missing = required_fields.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"direction_lookup.csv is missing required columns: {', '.join(sorted(missing))}"
            )

        for row in reader:
            name = (row.get("name") or "").strip()
            anchor_cid = (row.get("anchor_cid") or "").strip()

            if not name:
                raise ValueError(f"Direction row missing 'name': {row!r}")
            if not anchor_cid:
                raise ValueError(f"Direction row missing 'anchor_cid': {row!r}")

            conn.execute(
                """
                INSERT INTO directions (name, anchor_cid)
                VALUES (?, ?)
                """,
                (name, anchor_cid),
            )

    print("✅ Direction import complete.")
